baseurl = "https://www.cstamas.org/"
title = "cstamas.org"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
pygmentsCodefences = true
pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
  author = "Tamás Cservenák"
  email = "tamas@cservenak.net"
  avatar = "avatar.jpg"
  favicon = "favicon.ico"
  error404 = "There is no such page. Move along..."
  description = """
  Resurrecting killed applications...<br/>
  and having fun.<br/>
  Proximity, Nexus, Maven and others...
  """
  publicationYear = "2024."
  # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
  # singlePageDateFormat = "January 2, 2006"
  # custom_css = ["/css/custom.css"]
  # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<span>Blog</span>" #Choose your favorite font from Font Awesome
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/cservenak"
    weight = 20

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/cstamas"
    weight = 30

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/cstamas"
    weight = 40

[[menu.main]]
    identifier = "gitlab"
    # name = "GitLab"
    pre = "<i class='fab fa-gitlab fa-lg'></i>"
    url = "https://gitlab.com/tamascs"
    weight = 50

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:tamas@cservenak.net"
    weight = 60
