baseurl = "https://www.cstamas.org/"
title = "cstamas.org"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = false
pygmentsCodefences = true
pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
  author = "Tamás Cservenák"
  email = "tamas@cservenak.net"
  avatar = "avatar.jpg"
  favicon = "favicon.ico"
  error404 = "There is no such page. Move along..."
  description = """
  Resurrecting killed applications...<br/>
  and having fun.<br/>
  Proximity, Nexus, Maven and others...
  """
  publicationYear = "2024."
  # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
  # singlePageDateFormat = "January 2, 2006"
  # custom_css = ["/css/custom.css"]
  # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "about"
    # name = "About" #If display text link, cancel comment out
    pre = "<i class='fa-solid fa-address-card fa-2xl' title='About'></i>"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa-brands fa-microblog fa-2xl' title='Blog'></i>"
    url = "/blog/"
    weight = 20

[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fa-brands fa-linkedin fa-2xl' title='LinkedIn'></i>"
    url = "https://www.linkedin.com/in/cservenak"
    weight = 30

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fa-brands fa-twitter fa-2xl' title='Twitter'></i>"
    url = "https://twitter.com/cstamas"
    weight = 40

[[menu.main]]
    identifier = "mastodon"
    # name = "Twitter"
    pre = "<i class='fa-brands fa-mastodon fa-2xl' title='Mastodon'></i>"
    url = "https://mastodon.online/@cstamas"
    weight = 50

[[menu.main]]
    identifier = "bluesky"
    # name = "Twitter"
    pre = "<i class='fa-brands fa-bluesky fa-2xl' title='BlueSky'></i>"
    url = "https://bsky.app/profile/cstamas.bsky.social"
    weight = 60

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fa-brands fa-github fa-2xl' title='Github'></i>"
    url = "https://github.com/cstamas"
    weight = 70

[[menu.main]]
    identifier = "gitlab"
    # name = "GitLab"
    pre = "<i class='fa-brands fa-gitlab fa-2xl' title='Gitlab'></i>"
    url = "https://gitlab.com/tcservenak"
    weight = 80

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-at fa-2xl' title='e-mail'></i>"
    url = "mailto:tamas@cservenak.net"
    weight = 90
