baseurl = "https://www.cstamas.org/"
title = "cstamas.org"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = false
pygmentsCodefences = true
pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe= true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  author = "Tamás Cservenák"
  email = "tamas@cservenak.net"
  avatar = "avatar.jpg"
  favicon = "favicon.ico"
  error404 = "There is no such page. Move along..."
  description = """
  Resurrecting killed applications...<br/>
  and having fun!<br/>
  Proximity, Nexus, Maven and others...
  """
  publicationYear = "2024."
  # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
  # singlePageDateFormat = "January 2, 2006"
  # custom_css = ["/css/custom.css"]
  # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "about"
    # name = "About" #If display text link, cancel comment out
    pre = "<i class='fa-solid fa-address-card fa-2xl' title='About'></i>"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa-brands fa-microblog fa-2xl' title='Blog'></i>"
    url = "/blog/"
    weight = 20

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-at fa-2xl' title='e-mail'></i>"
    url = "mailto:tamas@cservenak.net"
    weight = 90
